language: node_js

node_js:
- '8'
- '6'

install:
- yarn install

script:
- yarn build
- yarn lint
- yarn test

before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script: npm publish .
  on:
    tags: true
